# Generated by Django 5.2.7 on 2025-12-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='joined_clubs', to='accounts.student'),
        ),
    ]
